### ISSUE TITLE
Output as features

### ISSUE THREAD

**Issue by leonardosegurat** [biolab/orange3-survival-analysis#55]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to use the selected features on Rank Survival Features and Stepwise Cox Regression as an input for Select Columns widget, unlike the "regular" Rank widget.

This is useful when you're looking to compare different feature selection methods with the same train/test data sampling before regression.

**Describe the solution you'd like**
Update Rank Survival Features and Stepwise Cox Regression to have a "Features" output for feature selection.

**Describe alternatives you've considered**
I found a workaround by sending data output to Rank widget, configuring it to select all, and using Rank's feature output as an input for Select Columns, tough that is a bit convoluted and unintuitive for the user.

**Additional context**
Example workflow using Rank workaround.
![image](https://user-images.githubusercontent.com/21146125/202516071-3ba5d25a-e8c6-4699-a3a7-8f083e1fb7ae.png)

**Comment by JakaKokosar** [comment]
Interestingly, thank you. I will see what can be done and will let you know.

**Comment by JakaKokosar** [comment]
@leonardosegurat, this will be included in the next release. Thank you for noticing this! If you have any other suggestions/comments or have problems, please reach out.

![Screenshot 2022-12-06 at 12 01 10](https://user-images.githubusercontent.com/15876321/205894467-e99b698a-8953-4295-b2d1-7b315dd6fdeb.png)
